config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  
  resources :users, only:[:new, :create, :update,:edit]

  resources :ideas do 
   resources :likes, shallow: true, only: [:create, :destroy]

   resources :reviews, only: [:create, :destroy]
  end
  root 'ideas#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  

  def initialize(user)
   
      user ||= User.new
  
    # if user.is_admin?
    #   can :manage, :all 
    # end
    
    can(:crud, Idea) do |idea| 
      idea.user == user 
    end
   
    can(:crud, Review) do |review|
      review.user == user 
   
    end

    can(:like, Idea) do |idea|
      user.persisted? && idea.user != user

    end


    can(:destroy, Like) do |like|
      like.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many(:reviews,dependent: :destroy)
    validates(:title, presence: true, uniqueness: true)
    
    has_many :likes
    has_many :likers, through: :likes, source: :user
    
    validates(
        :description,
        presence: { message: "must exist" }
    )
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates(
    :idea_id,
    uniqueness: {
      scope: :user_id,
      message: "has already been liked"
    }
  )
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :ideas
    has_many :reviews
    has_many :likes
    has_many :liked_ideas, through: :likes, source: :idea
    
    
    validates(:email, presence: true, uniqueness: true, format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
    validates(:name, presence: true)
    validates(:password, presence: true)
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        if session[:user_id].present?
          @current_user ||= User.find session[:user_id] 
        end
    end
    
     helper_method :current_user
    
    def user_signed_in?
      current_user.present?
    end
      helper_method :user_signed_in?
    
    def authenticate_user!
        unless user_signed_in?
          flash[:danger] = "You need to be signed in first!"
          redirect_to new_session_path
        end
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show] 
    before_action :authorize!, only: [:edit, :update, :destroy]
  
        def index
          @ideas = Idea.all.order('updated_at DESC')
         

        end
      
        def new
          @idea = Idea.new # we need an instance of our resource to be used with `form_with`
        end
        
        def create
          @idea = Idea.new(params.require(:idea).permit(:title, :description))
          @idea.user = current_user
          if @idea.save
              redirect_to ideas_path
            else
              render :new
            end
        end 
        def show
          id = params[:id]
          @idea = Idea.find(id)
          @review = Review.new 
         @reviews = @idea.reviews.order(created_at: :desc)
         @like = @idea.likes.find_by(user: current_user)
        end
        
        def edit
          id = params[:id]
          @idea = Idea.find(id)
        end 
        
        def update
          id = params[:id]
          @idea = Idea.find(id)
          if @idea.update(params.require(:idea).permit(:title, :description))
             redirect_to idea_path(@idea)
          else
             render :edit
          end
        end
  
        
        def destroy
          id = params[:id]
          @idea = Idea.find(id)
          @idea.destroy
          redirect_to ideas_path
        end
        private
        def authorize! 
          redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, Idea)
        end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy] 

    def create
   
        idea = Idea.find params[:idea_id]
        like = Like.new(idea: idea, user: current_user)
    
        if !can?(:like,idea)
          flash[:danger] = "You can't like your own Idea..."
        elsif like.save
          flash[:success] = "Idea Liked"
        else
          flash[:danger] = like.errors.full_messages.join(", ")
        end
        redirect_to ideas_path(idea)
      end
    
      def destroy
        
        like = current_user.likes.find params[:id] 
        if !can?(:destroy, like)
          flash[:warning] = "you can't destroy a like you don't own"
        elsif like.destroy
          flash[:success] = "Idea Un-liked"
        else
          flash[:warning] = "It's rude to unlike something you've already liked"
        end
        redirect_to ideas_path
      end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create 
        @idea = Idea.find(params[:idea_id])
        @review = Review.new review_params
        @review.idea = @idea
        @review.user = current_user
        if @review.save
            redirect_to idea_path(@idea)
        else
            @reviews = @idea.reviews.order(created_at: :desc)
            render 'ideas/show'
        end
    end

    def destroy 
            @review = Review.find params[:id]
       if can?(:crud, @review) 
            @review.destroy 
            redirect_to idea_path(@review.idea)
       else
            head :unauthorized
       end
    end


    private 
    
    def review_params 
        params.require(:review).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by_email params[:email]
        
        if user&.authenticate params[:password]
          session[:user_id] = user.id
          session[:color] = 'blue'
        
          flash[:success] = "User Logged In"
          redirect_to ideas_path
        else
          flash[:warning] = "Couldn't log In"
          render :new
        end
      end
      def destroy
        session[:user_id] = nil
        redirect_to ideas_path
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     def new
        if user_signed_in?
          flash[:warning] = "Can't create new account while signed in"
          redirect_to ideas_path
        else 
          @user = User.new
        end
     end
    
      def create
        @user = User.new params.require(:user).permit(:name, :email, :password, :password_confirmation)
        if @user.save
          flash.delete(:warning)
          redirect_to new_session_path
        else
          flash[:warning] = "Unable to create user"
          render :new
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<% if @idea.errors.present? %>
  <p>
    <%= @idea.errors.full_messages.join(', ')%>
  </p>
<% end %>

<div class = "container">
<%= form_with model: @idea, local:true do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field(:title, class: 'form-control')%>
  </div>
  <div class='form-group'>
    <%= f.label :description%>
    <%= f.text_area(:description, class: 'form-control', cols: 50, rows: 5)%>
  </div>
  <%= f.submit "Create", class: 'btn btn-outline-primary' %>
<% end %>

app/views/ideas/edit.html.erb
<%= render 'form' %>

app/views/ideas/index.html.erb
<div class='row'>
  <div class='col-2'>
  </div>
  <div class='col-10'>
   <div class= 'container'>
    <% @ideas.each do |idea| %>
    <%# if you pass a instance to link_to it will create the href='/questions/:id' %>
    <div>
      <hr>
      <div>
      <%= link_to idea do %>
        <li>
          <strong><%= idea.title %></strong>
         </li>
      <% end %>
      </div>
      <div>
        <p ><%= idea.description  %> </p>
      </div>
      <div>
       <small>By: <u><%= idea.user.name%></u></small>
       <strong>Likes: <%= idea.likes.count %></strong>
      <div class="float-right">
      <div class="d-flex justify-content-around align-items-end">
       
   
        
    
<% if idea.likes.find_by(user: current_user).present?%>
      <%= link_to(
          "Unlike",
          like_path(idea.likes.find_by(user: current_user)),
          method: :delete, 
          class: 'btn btn-danger'
        )
      %>
    <% else %>
      <%= link_to(
          "Like",
          idea_likes_path(idea),
          method: :post,
          class: 'btn btn-primary'
        )
      %>
    <% end %>
          
        </div>
      </div>
    <% end %>  
    </div>
    </div>
  </div>
</div>

app/views/ideas/new.html.erb
<div class = "container">
<h1>
  New Idea Page
</h1>
<div>
<%= render 'form' %>

app/views/ideas/show.html.erb
<div class = "container">
  <div class="shadow-sm p-3 mb-5 bg-white rounded overflow-wrap">
    <h1>
      <%= @idea.title %>
    </h1>
    <p class="shadow-none p-3 mb-5 bg-light rounded"><%= @idea.description %></p>
    <p class='text-muted'><%= @idea.user.name %> 
    <small>Liked by: <%= @idea.likes.count %></small>
     <small>
    <% if @like.present? %>
      <%= link_to(
          "Unlike",
          like_path(@like),
          method: :delete, 
          class: 'btn btn-danger'
        )
      %>
    <% else %>
      <%= link_to(
          "Like",
          idea_likes_path(@idea),
          method: :post,
          class: 'btn btn-primary'
        )
      %>
    <% end %>
  </small>

    <%# link_to arguments: name, path, ostions_object %>
    <% if can? :crud, @idea %>
    <div>
      <%= link_to( "Edit", edit_idea_path(@idea), class: 'btn btn-outline-primary') %> 
      <%= link_to( "Delete", idea_path(@idea), method: :delete, class: 'btn btn-outline-primary', data: { confirm: 'are you sure?' } ) %>
      </div>
    </div>
    <% end %> 

  <%= form_with(model: [@idea, @review], local: true) do |f| %> <% if
  @review.errors.full_messages.each do |msg| %>
  <ul>
    <li class="text-danger"><%= msg %></li>
  </ul>
  <% end %> <% end %>
  <div class="form-group">
    <%= f.text_area( :body, cols: 50, rows: 5, placeholder: "Any suggestions you have?", class: "form-control" ) %>
  </div>
  <%= f.submit "Submit", class: "btn btn-outline-primary" %> <br>
  <br>
  <% end %>

  <ul class="list-group review-list">
    <% @reviews.each do |review| %>
    <li class="list-group-item">
      <p>
        <%= review.body %><br />
        <small>
     Review Added:  <%= time_ago_in_words(review.created_at) %> By <%= review.user.name %> 
        </small>	       
        <% if can? :crud, review %>
        <small>
          <%= link_to( "Delete", idea_review_path(@idea, review), method:
          :delete, data: { confirm: "Are you sure?" }, class: 'text-primary', ) %>
        </small>
        <% end %> 
      </p>
    </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Idea Factory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
   
   <%= render 'shared/navbar' %>
      
      <% flash.each do |type, message| %>
        <div class='bg-<%= type %> p-3 rounded mb-2 shadow-sm'>
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
  
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
    <div style="width: 20%;">
      <a class="navbar-brand text-primary" href = "/">Idea Factory</a>
    </div>
    <div style="width: 80%;">
      <div class="float-right" style="width: 25%;">
        <div class="d-flex justify-content-end align-items-end">
         
     <% if user_signed_in? %>
       <h5 class="nav-item text-dark"><%= current_user.name%> |  </h5> 

      <%= link_to "Logout", session_path, method: :delete, class: 'btn btn-danger' %>

     <% else %>    
      <%= link_to "Log In", new_session_path, class: 'btn btn-primary'%>
      <%= link_to "Sign Up", new_user_path, class: 'btn btn-warning' %>
     <% end %>
       </div>
       <br>
      <div class="d-flex justify-content-end align-items-end">

        <a href="/ideas/new">
            <h5 class="nav-item text-primary">New Idea</h5>
          </a>
          
       </div>   
      </div>
    </div>
  </nav>

app/views/users/new.html.erb
<h1>User New Page</h1>
<% if @user.errors.present? %>
  <p>
    <%= @user.errors.full_messages.join(', ')%>
  </p>
<% end %>
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <%= form_with model: @user, local: true do |f| %>
    <div class='form-group'>
      <%= f.label :name%>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :email%>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password%>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit "Create User", class: 'btn btn-primary' %>
  <% end %>
</div> 